# This chart catches changes and then pushed to main branch
# Tests, Updates Dependency and Packages, then pushes to 
# our parent repo that holds all Helx Charts Helm-Charts

name: Package-To-Helm-Charts-Repo
on:
  push:
    branches:
      - develop
      # - master
      # - main
jobs:
  package-to-helx:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }} 
        fetch-depth: 0

############################# Lint-Test #########################
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.2

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        check-latest: true

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.4.0

    - name: Run chart-testing (list-changed)
      id: list-changed
      run: |
        changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
        if [[ -n "$changed" ]]; then
          echo "changed=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Run chart-testing (lint)
      if: steps.list-changed.outputs.changed == 'true'
      run: ct lint --target-branch ${{ github.event.repository.default_branch }}

    - name: Create kind cluster
      if: steps.list-changed.outputs.changed == 'true'
      uses: helm/kind-action@v1.4.0

    - name: Run chart-testing (install)
      if: steps.list-changed.outputs.changed == 'true'
      run: ct install --target-branch ${{ github.event.repository.default_branch }}

#################### Package & Push to Helm-Charts ######################    
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}

    - name: Package Chart 
      run: |
        helm package --dependency-update ${{ github.workspace }} --destination /tmp/${{ github.repository_owner }}

    - name: Get package name 
      id: name 
      run: |
        echo "chart_name=$(ls /tmp/${{ github.repository_owner }}/)" >> $GITHUB_OUTPUT
        ls /tmp/${{ github.repository_owner }}

    - name: Upload artifact 
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.name.outputs.chart_name }}
        path: /tmp/${{ github.repository_owner }}/${{ steps.name.outputs.chart_name }}.tgz

    # - name: Push to Helm-Charts /docs Directory
      